### ISSUE TITLE
Nuevas funcionalidades

### ISSUE THREAD

**Issue by dagoull** [alu0101325781/Finalproject-LyDH#1]
**Implementar algunas de estas funcionalidades**

- Modo multijugador: Podría ser interesante añadir un modo multijugador en el que los jugadores compitan entre sí para alcanzar el número 2048 primero.
- Niveles de dificultad: Se podrían introducir diferentes niveles de dificultad, por ejemplo, aumentando el tamaño de la cuadrícula o cambiando la frecuencia con la que aparecen los números más altos.
- Tablas de clasificación: Las tablas de clasificación permiten a los jugadores comparar sus puntuaciones con las de otros jugadores de todo el mundo.
- Personalización: Permitir a los jugadores personalizar el aspecto del juego, como los colores de las fichas y el fondo, puede aumentar el atractivo visual del juego.
- Modo sin fin: Después de alcanzar el número 2048, se podría permitir a los jugadores continuar jugando para ver qué tan alto pueden llegar.
- Guardado automático: Asegurarse de que el juego se guarda automáticamente puede ser útil para los jugadores que quieren hacer una pausa y continuar más tarde.

**Comment by FrancescoMarelli** [comment]
Se han creado 4 funcionalidades en distintas ramas por los cuatros componentes del equipo.

- Dificultad añadiendo más baldosas en cada iteración.
- Se ha creado el botón de finalizar partido y una tabla de clasificación.
- Se ha creado un menu con la opción de elegir el estilo de juego.
- Modo sin fin.
